services:
  api:
    image: pangolin
    build:
      context: pangolin-app/api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      #DATABASE_PASSWORD: ./secrets/db_password
    ports:
      - 3000:3000
    env_file: pangolin-app/api/.env
    secrets:
      - db_password
  frontend:
    image: pangolin-frontend
    build:
      context: pangolin-app/frontend
      dockerfile: dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
secrets:
  db_password:
    file: ./db_password.txt