FROM node:22.4.0-alpine
#ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "angular.json*", "./"]
COPY . .
RUN echo "npm install"
RUN npm install 
RUN echo "angular install"
RUN npm install -g @angular/cli
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]